# Generated by Django 4.0.1 on 2022-01-15 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('className', models.CharField(max_length=50)),
                ('teacherName', models.CharField(max_length=50)),
                ('classCode', models.UUIDField(default=uuid.UUID('ab0f5468-bc99-478b-b504-5e71898622a0'), editable=False, primary_key=True, serialize=False)),
                ('usercode', models.UUIDField(default=None, editable=False, null=True)),
                ('videoStreamURL', models.URLField(default=None, null=True)),
                ('classAvatarURL', models.URLField(default=None, null=True)),
                ('studentList', models.TextField(default=None, null=True)),
            ],
        ),
    ]
