# Generated by Django 4.0.1 on 2022-01-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('avatarURL', models.URLField(default=None)),
                ('description', models.TextField(default=None)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmPassword',
        ),
        migrations.AddField(
            model_name='user',
            name='uniquecode',
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
    ]
