# Generated by Django 4.0.1 on 2022-01-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_uniquecode_user_usercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usercode',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
    ]
