# Generated by Django 4.0.1 on 2022-01-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasses',
            name='classCode',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentclasses',
            name='usercode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
