# Generated by Django 4.0.1 on 2022-02-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentclasses_classcode_studentclasses_usercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('usercode', models.CharField(max_length=50, null=True)),
                ('classCode', models.CharField(max_length=50)),
            ],
        ),
    ]
